# Generated by Django 3.2.7 on 2021-09-17 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('type', models.CharField(choices=[('student', 'student'), ('teacher', 'teacher'), ('school', 'school')], max_length=7)),
            ],
        ),
    ]
