# Generated by Django 3.2.7 on 2021-09-17 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_accounts_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('plan', models.CharField(choices=[('standard', 'standard'), ('hacker', 'hacker'), ('premium', 'premium')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('grade', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.school')),
            ],
        ),
    ]
