# Generated by Django 3.2.7 on 2021-09-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_school_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='plan',
            field=models.CharField(choices=[('standard', 'standard'), ('hacker', 'hacker'), ('premium', 'premium')], default='standard', max_length=8),
        ),
    ]
