# Generated by Django 3.2.7 on 2021-09-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_student_grade'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chat',
            new_name='chat_room',
        ),
    ]
