# Generated by Django 3.2.7 on 2021-09-20 16:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_student_grade'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='school',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='users.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circular',
            name='school',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='users.school'),
            preserve_default=False,
        ),
    ]
