# Generated by Django 3.2.7 on 2021-09-21 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_ebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='ebooks'),
            preserve_default=False,
        ),
    ]
