# Generated by Django 3.2.7 on 2021-09-21 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
