# Generated by Django 3.2.7 on 2021-09-21 15:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_student_grade'),
        ('dashboard', '0007_classes_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='users.teacher'),
            preserve_default=False,
        ),
    ]
