# Generated by Django 3.2.7 on 2021-09-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_circular_circular_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circular',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
